style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitee.com/quant1x/autochangelog
options:
  tag_filter_pattern: '^v'
  commits:
    # filters:
    #   Type: []
  commit_groups:
    # title_maps: []
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE